### ISSUE TITLE
Syntax Typo in README.md

### ISSUE THREAD

**Issue by manishram** [seed-of-apricot/issue-list-readme#10]
There is a typo error(marked as **bold** below):

with:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      pattern: '' # suffixing "Demo" for this readme
      labels: 'good first issue'
      **labels**: 'open'

**label** should be replaced with **status**

**Comment by seed-of-apricot** [comment]
@manishram Sorry I didn't notice your PR (just checked the repo issues as I saw a new-issue notification via email)!
I supposed this is almost only for my internal use but am glad to hear some feedback :)
