### ISSUE TITLE
Getting file not found error when README.md exists.

### ISSUE THREAD

**Issue by mmattbtw** [seed-of-apricot/issue-list-readme#8]
`Error: ENOENT: no such file or directory, open './README.md'`

[My README.md file](https://github.com/DoobDev/Doob/blob/master/README.md)

**Comment by seed-of-apricot** [comment]
@mmattbtw Sorry I didn't notice this one (just checked the repo issues as I saw a new-issue notification via email)!
I guess you've already gone to another solution...
