### ISSUE TITLE
Nothing is added to README.md

### ISSUE THREAD

**Issue by mahdi** [seed-of-apricot/issue-list-readme#9]
It looks everything's fine in my job but no open issues are being added to my README.me: [https://github.com/mahdi/pokespeare](https://github.com/mahdi/pokespeare)

<img width="407" alt="Screen Shot 2020-11-14 at 16 47 35" src="https://user-images.githubusercontent.com/67627/99152363-3c647380-2699-11eb-8e17-ec1ee66c3eed.png">

**Comment by manishram** [comment]
@mahdi you also need **add and commit** and **push** actions as clearly stated in the README.md file.

``` - name: add-and-commit
        uses: EndBug/add-and-commit@v4
        with:
          message: README.md has been re-written
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
```

You can also check the yml file of this repository:
https://github.com/seed-of-apricot/issue-list-readme/blob/master/.github/workflows/rewriteReadme.yml
